language: cpp

before_install:
  - sudo apt install nasm -y
  - sudo apt install g++ -y
  - sudo apt install make -y
  - sudo apt install gcc -y
  - sudo apt install xorriso -y
  - sudo apt install build-essential -y

script:
  - make clear
  - make kernel
  - make loader
  - make link
  - make iso
